/*
 * Autogenerated by the Meson build system.
 * Do not edit, your changes will be lost.
 */

#pragma once

#undef BIGENDIAN

#define TW_VERSION_STRING "5.0.0"

#define USE_DESKTOP

#undef USE_HPC

#undef USE_OPENCL

#define USE_OPENMP

#undef USE_TWSF

#define VBITS 256

