/**
 * @brief This module was generated by Gemini Enterprise with slight tweaks.
 *        For decades, we used std::valarray as the underlying storage for everything.
 *        We now have the abstract wrapper tw::vec which currently wraps std::vector.
 */
export module tw_vec;

import std;

export namespace tw {

    template <typename T>
    class vec {
    private:
        std::vector<T> m_data;

    public:
        // --- Standard Type Aliases ---
        using value_type = T;

        // --- Constructors ---
        vec() = default;
        explicit vec(std::size_t count) : m_data(count) {}
        vec(const T& val, std::size_t count) : m_data(count, val) {}
        vec(const T* vals, std::size_t count) : m_data(vals, vals + count) {}
        vec(const vec&) = default;
        vec(vec&&) noexcept = default;
        vec(std::initializer_list<T> il) : m_data(il) {}

        // --- Assignment ---
        vec& operator=(const vec&) = default;
        vec& operator=(vec&&) noexcept = default;
        vec& operator=(std::initializer_list<T> il) {
            m_data = il;
            return *this;
        }
        vec& operator=(const T& val) {
            std::fill(m_data.begin(), m_data.end(), val);
            return *this;
        }

        // --- Access & Capacity ---
        std::size_t size() const { return m_data.size(); }
        void resize(std::size_t count, T val = T()) { m_data.resize(count, val); }
        
        T* data() noexcept { return m_data.data(); }
        const T* data() const noexcept { return m_data.data(); }

        T& operator[](std::size_t index) { return m_data[index]; }
        const T& operator[](std::size_t index) const { return m_data[index]; }

        // --- Utility methods ---
        T sum() const {
            return std::reduce(m_data.begin(), m_data.end(), T{});
        }

        T min() const {
            return *std::min_element(m_data.begin(), m_data.end());
        }

        T max() const {
            return *std::max_element(m_data.begin(), m_data.end());
        }

        vec shift(int count) const {
            vec result(this->size());
            if (std::abs(count) >= this->size()) return result;
            
            if (count > 0) {
                std::copy(m_data.begin() + count, m_data.end(), result.m_data.begin());
            } else {
                std::copy(m_data.begin(), m_data.end() + count, result.m_data.begin() - count);
            }
            return result;
        }

        vec cshift(int count) const {
            if (m_data.empty()) return *this;
            vec result = *this;
            count %= static_cast<int>(m_data.size());
            if (count < 0) count += m_data.size();
            
            std::rotate(result.m_data.begin(), result.m_data.begin() + count, result.m_data.end());
            return result;
        }

        // Accepts any callable (functors, lambdas, etc.)
        template <typename F>
        vec apply(F&& func) const {
            vec result(this->size());
            for (std::size_t i = 0; i < m_data.size(); ++i) {
                result[i] = std::invoke(std::forward<F>(func), m_data[i]);
            }
            return result;
        }

        // --- Element-wise Compound Assignment ---
        #define VEC_COMP_OP(OP) \
        vec& operator OP(const vec& rhs) { \
            for (std::size_t i = 0; i < m_data.size(); ++i) m_data[i] OP rhs[i]; \
            return *this; \
        } \
        vec& operator OP(const T& val) { \
            for (auto& elem : m_data) elem OP val; \
            return *this; \
        }

        VEC_COMP_OP(+=)
        VEC_COMP_OP(-=)
        VEC_COMP_OP(*=)
        VEC_COMP_OP(/=)
        #undef VEC_COMP_OP

        std::vector<T>& std_vector() { return m_data; }
        const std::vector<T>& std_vector() const { return m_data; }
    };

    // --- Non-member Binary Operators ---
    #define VEC_BIN_OP(OP, COMP_OP) \
    template <typename T> \
    vec<T> operator OP(vec<T> lhs, const vec<T>& rhs) { \
        lhs COMP_OP rhs; return lhs; \
    } \
    template <typename T> \
    vec<T> operator OP(vec<T> lhs, const T& val) { \
        lhs COMP_OP val; return lhs; \
    } \
    template <typename T> \
    vec<T> operator OP(const T& val, vec<T> rhs) { \
        vec<T> res(rhs.size()); \
        for(std::size_t i=0; i<rhs.size(); ++i) res[i] = val OP rhs[i]; \
        return res; \
    }

    VEC_BIN_OP(+, +=)
    VEC_BIN_OP(-, -=)
    VEC_BIN_OP(*, *=)
    VEC_BIN_OP(/, /=)
    #undef VEC_BIN_OP

    // --- Math Overloads (ADL-Friendly) ---
    template <typename T>
    vec<T> sin(const vec<T>& v) {
        return v.apply([](const T& x) { return std::sin(x); });
    }

    template <typename T>
    vec<T> cos(const vec<T>& v) {
        return v.apply([](const T& x) { return std::cos(x); });
    }

    template <typename T>
    vec<T> exp(const vec<T>& v) {
        return v.apply([](const T& x) { return std::exp(x); });
    }

    template <typename T>
    vec<T> abs(const vec<T>& v) {
        return v.apply([](const T& x) { return std::abs(x); });
    }

} // namespace tw
