name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Install dependencies
      run: |
        conda install -c dfxgordon twutils
    - name: setup
      working-directory: ./core/source
      run: meson setup build
    - name: configure
      working-directory: ./core/source/build
      run:  meson configure -Domp=true -Docl=false
    - name: build
      working-directory: ./core/source/build
      run: meson compile
    - name: turbowave unit testing
      working-directory: ./core/source/build
      run: ./tw3d -n 2 --unit-test --all
    - name: turbowave integration testing
      run: twtest --integration --root . --command ./core/source/build/tw3d -n 4
