name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up CMake
      uses: lukka/get-cmake@latest
    - name: Install GCC 14
      run: |
        sudo apt install gcc-14
        sudo apt install libstdc++-14-dev
    - name: Install OpenMPI
      run: sudo apt install libopenmpi-dev
    - name: Install Homebrew LLVM
      run: |
        eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
        brew install llvm
    - name: Build
      working-directory: ./core/source
      run: |
        mkdir build
        cd build
        eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
        cmake -G Ninja ..
        cmake --build .
    - name: turbowave unit testing
      working-directory: ./core/source/build
      run: ./tw3d -n 2 --unit-test --all
    # - name: Set up Python 3.13
    #   uses: actions/setup-python@v5
    #   with:
    #     python-version: '3.13'
    # - name: Add conda to system path
    #   run: |
    #     # $CONDA is an environment variable pointing to the root of the miniconda directory
    #     echo $CONDA/bin >> $GITHUB_PATH
    # - name: Install dependencies
    #   run: |
    #     conda install -c dfxgordon twutils
    # - name: turbowave integration testing
    #   run: twtest --integration --root . --command ./core/source/build/tw3d -n 4
