name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-2025

    steps:
    - uses: actions/checkout@v4
    - name: Set up CMake
      uses: lukka/get-cmake@latest
    - name: Set up MS-MPI
      shell: powershell
      run: |
        Invoke-WebRequest -Uri "https://github.com/microsoft/Microsoft-MPI/releases/download/v10.1.1/msmpisetup.exe" -OutFile msmpisetup.exe
        Invoke-WebRequest -Uri "https://github.com/microsoft/Microsoft-MPI/releases/download/v10.1.1/msmpisdk.msi" -OutFile msmpisdk.msi
        Start-Process -FilePath msmpisetup.exe -ArgumentList "/quiet /norestart" -Wait
        Start-Process -FilePath msmpisdk.msi -ArgumentList "/quiet /norestart" -Wait
    - name: Set MS-MPI Environment Variables
      shell: powershell
      run: |
        echo "MSMPI_INC=C:\Program Files (x86)\Microsoft SDKs\MPI\Include" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
        echo "MSMPI_LIB64=C:\Program Files (x86)\Microsoft SDKs\MPI\Lib\x64" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
    - name: setup
      working-directory: ./core/source
      run: mkdir build
    - name: build
      working-directory: ./core/source/build
      run: | 
        cmake -G Ninja ..
        cmake --build .
    - name: turbowave unit testing
      working-directory: ./core/source/build
      run: ./tw3d -n 2 --unit-test --all
    # - name: Set up Python 3.13
    #   uses: actions/setup-python@v5
    #   with:
    #     python-version: '3.13'
    # - name: Add conda to system path
    #   run: |
    #     # $CONDA is an environment variable pointing to the root of the miniconda directory
    #     echo $CONDA/bin >> $GITHUB_PATH
    # - name: Install dependencies
    #   run: |
    #     conda install -c dfxgordon twutils
    # - name: turbowave integration testing
    #   run: twtest --integration --root . --command ./core/source/build/tw3d -n 4
